### ISSUE TITLE
Not able to switch audio devices after 1.4.5 update

### ISSUE THREAD

**Issue by marcinjahn** [AvengeMedia/DankMaterialShell#2294]
### Compositor

Niri

### Distribution

Fedora

### Select your Installation Method

DankInstaller

### Was this your original Installation method?

Yes

### dms doctor -vC

<details>
<summary>Click to expand</summary>

## DMS Doctor Report

**System**
- [ok] Operating System: Fedora Linux 43 (Workstation Edition)
  - ID: fedora, Version: 43, Arch: amd64
- [ok] Architecture: amd64
- [ok] Display Server: Wayland
  - WAYLAND_DISPLAY=wayland-1

**Versions**
- [ok] DMS CLI: dms v1.4.5
  - /usr/bin/dms
- [ok] Quickshell: Quickshell 0.2.1 (revision 783c953987dc56ff0601abe6845ed96f1d00495a, distributed by Fedora COPR (avengemedia/quickshell))
  - /usr/bin/qs
- [ok] DMS Shell: 1.4.5
  - /usr/share/quickshell/dms

**Installation**
- [ok] DMS Configuration: Found
  - /usr/share/quickshell/dms
- [ok] shell.qml: Present
  - /usr/share/quickshell/dms/shell.qml
- [info] Install Type: System package
  - /usr/share/quickshell/dms

**Compositor**
- [ok] niri: 26.04
  - /usr/bin/niri
- [info] Active: niri
- [ok] Background Blur: Supported
  - Compositor supports ext-background-effect-v1

**Quickshell Features**
- [ok] Polkit: Available
  - Authentication prompts
- [ok] IdleMonitor: Available
  - Idle detection
- [ok] IdleInhibitor: Available
  - Prevent idle/sleep
- [ok] ShortcutInhibitor: Available
  - Allow shortcut management (niri)
- [ok] BackgroundBlur: Available
  - Background blur API support in Quickshell

**Optional Features**
- [ok] accountsservice: Available
  - User accounts
- [ok] power-profiles-daemon: Available
  - Power profile management
- [ok] logind: Available
  - Session management
- [ok] cups-pk-helper: Available
  - Printer management
- [info] I2C/DDC: No monitors detected
  - External monitor brightness control
- [ok] qt6-imageformats: Installed (1 formats)
  - Formats: GIF (/usr/lib64/qt6/plugins/imageformats)
- [ok] kimageformats: Installed (4 formats)
  - Formats: AVIF, HEIF, JXL, EXR (/usr/lib64/qt6/plugins/imageformats)
- [ok] Terminal: alacritty
- [ok] Network: NetworkManager
  - NetworkManager present. Using NM API.
- [ok] matugen: Installed
  - Dynamic theming
- [ok] dgop: Installed
  - System monitoring
- [ok] cava: Installed
  - Audio visualizer
- [info] khal: Not installed
  - Calendar events
- [ok] danksearch: Installed
  - File search
- [ok] fprintd: Installed
  - Fingerprint auth

**Config Files**
- [ok] settings.json: Present
  - /home/mnj/.config/DankMaterialShell/settings.json
- [ok] clsettings.json: Present
  - /home/mnj/.config/DankMaterialShell/clsettings.json
- [ok] plugin_settings.json: Present
  - /home/mnj/.config/DankMaterialShell/plugin_settings.json
- [ok] session.json: Present
  - /home/mnj/.local/state/DankMaterialShell/session.json
- [ok] dms-colors.json: Present
  - /home/mnj/.cache/DankMaterialShell/dms-colors.json

**Services**
- [ok] dms.service: enabled, active
- [info] greetd: Not installed
  - Optional greeter service

**Environment**
- [info] QT_QPA_PLATFORMTHEME: gtk3
- [info] QS_ICON_THEME: Not set

---
**Summary:** 0 error(s), 0 warning(s), 34 ok

</details>

### Description

After updating to 1.4.5, the quick settings panel no longer allows me to change autdio input or output. The options are listed there, but clicking on any other device than currently selected one doesn't change it.

### Expected Behavior

I should be able to switch devices from quick setting menu

### Steps to Reproduce

1. Open quick settings menu
2. Try to change the output or input device

### Error Messages/Logs

I see this log in `journalctl` when I click on a different device than currently selected:

```
kwi 28 06:57:11 mj-lap dms[5796]:   WARN scene: @Modules/ControlCenter/Details/AudioOutputDetail.qml[361:-1]: TypeError: Property 'setDefaultSinkByName' of object AudioService_QMLTYPE_15(0x7f0788b5b180) is not a function
```

### Screenshots/Recordings

https://github.com/user-attachments/assets/7b5dbd62-43bb-47ae-a4c6-9160cf72c022

**Comment by bushblade** [comment]
I am also seeing the same issue after updating to 1.4.5

**Comment by marcinjahn** [comment]
Turns out this is already fixed on master branch. If you don't want to check for the formal release, you can patch it locally (as I did).

You nee to create a patch file `dms-audio.patch` somewhere on your system:

```
--- a/Services/AudioService.qml
+++ b/Services/AudioService.qml
@@ -71,6 +71,36 @@
         return Pipewire.nodes.values.filter(node => node.audio && node.isSink && !node.isStream && !hidden.includes(node.name));
     }

+    // Resolve a PwNode by name from the live typed list and assign it as the
+    // default sink. Going through Pipewire.nodes.values directly (no .filter
+    // / spread / .sort / property var) avoids QML type erasure to QObject*,
+    // which newer quickshell rejects when assigning to preferredDefaultAudioSink.
+    function setDefaultSinkByName(name) {
+        if (!name)
+            return false;
+        for (let i = 0; i < Pipewire.nodes.values.length; i++) {
+            const node = Pipewire.nodes.values[i];
+            if (node && node.name === name && node.audio && node.isSink && !node.isStream) {
+                Pipewire.preferredDefaultAudioSink = node;
+                return true;
+            }
+        }
+        return false;
+    }
+
+    function setDefaultSourceByName(name) {
+        if (!name)
+            return false;
+        for (let i = 0; i < Pipewire.nodes.values.length; i++) {
+            const node = Pipewire.nodes.values[i];
+            if (node && node.name === name && node.audio && !node.isSink && !node.isStream) {
+                Pipewire.preferredDefaultAudioSource = node;
+                return true;
+            }
+        }
+        return false;
+    }
+
     function cycleAudioOutput() {
         const sinks = getAvailableSinks();
         if (sinks.length < 2)
```

Then:

```sh
# Back up the original for safety
sudo cp -p /usr/share/quickshell/dms/Services/AudioService.qml /usr/share/quickshell/dms/Services/AudioService.qml.bak

# Dry-run the patch first to confirm it applies cleanly
sudo patch --dry-run -d /usr/share/quickshell/dms -p1 < dms-audio.patch

# Apply for real
sudo patch -d /usr/share/quickshell/dms -p1 < dms-audio.patch

# Restart dms
dms restart
```

Works for me.
